# Generated by Django 6.0.1 on 2026-02-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('customer', 'customer'), ('business', 'business')], default='customer', max_length=20),
        ),
    ]
